print("---------- Exercise 3-4 ----------")
guests=["Albert Einstein","Isaac Newton","Stephen Hawking"]
print(guests[0], "would you join me for dinner?")
print(guests[1], "would you join me for dinner?")
print(guests[2], "would you join me for dinner?")
print("---------- Exercise 3-5 ----------")
print(guests[1], "can't make it.")
guests[1] = "Nikola Tesla"
print(guests[0], "would you join me for dinner?")
print(guests[1], "would you join me for dinner?")
print(guests[2], "would you join me for dinner?")
print("---------- Exercise 3-6 ----------")
print("We can invite more guests!")
guests.insert(0,"Galileo Galilei")
guests.insert(2,"Thomas Edison")
guests.append("Bejamin Franklin")
print("Let's invite",len(guests), "guests.")
print(guests[0], "would you join me for dinner?")
print(guests[1], "would you join me for dinner?")
print(guests[2], "would you join me for dinner?")
print(guests[3], "would you join me for dinner?")
print(guests[4], "would you join me for dinner?")
print(guests[5], "would you join me for dinner?")
print("---------- Exercise 3-7 ----------")
print("The party is ruined, we can only invite two guests!")
removed = guests.pop()
print(removed, "you are no longer invited.")
removed = guests.pop()
print(removed, "you are no longer invited.")
removed = guests.pop()
print(removed, "you are no longer invited.")
removed = guests.pop()
print(removed, "you are no longer invited.")
print(guests[0], "would you join me for dinner?")
print(guests[1], "would you join me for dinner?")
del guests[1]
del guests[0]
print("Final guest list: ",guests)